<a href="https://colab.research.google.com/github/niranjankumarprajapati17-cmd/Machine-learning-pipeline-data-preprocessing-/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One-Hot-Encodings

In [27]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df=pd.read_csv("Housing.csv")
Housing_area_1hot=df[["area","bedrooms","bathrooms"]]
Housing_area_1hot
Cat_Encoder=OneHotEncoder()
Housing_area_1hot=Cat_Encoder.fit_transform(Housing_area_1hot)

In [130]:
print(Housing_area_1hot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [8]:
print(df)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [11]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [12]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [14]:
Housing_area_1hot.data

array([1., 1., 1., ..., 1., 1., 1.])

In [17]:
Housing_area_1hot.toarray() # Finding array

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
Housing_area_1hot.todense() # Dense array to direct

matrix([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
Cat_Encoder=OneHotEncoder(sparse_output=False) # Dense array
Housing_area_1hot=Cat_Encoder.fit_transform(df[["area","bedrooms","bathrooms"]])

In [30]:
print(Cat_Encoder)

OneHotEncoder(sparse_output=False)

In [31]:
print(Housing_area_1hot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [33]:
Cat_Encoder.categories_ # To check category order.

[array([ 1650,  1700,  1836,  1905,  1950,  2000,  2015,  2135,  2145,
         2160,  2175,  2176,  2275,  2325,  2398,  2400,  2430,  2475,
         2500,  2520,  2550,  2610,  2640,  2650,  2684,  2700,  2747,
         2787,  2800,  2817,  2835,  2850,  2856,  2870,  2880,  2910,
         2953,  2970,  2990,  3000,  3036,  3040,  3060,  3069,  3090,
         3100,  3120,  3150,  3162,  3180,  3185,  3210,  3240,  3264,
         3290,  3300,  3350,  3360,  3400,  3410,  3420,  3450,  3460,
         3480,  3500,  3510,  3512,  3520,  3540,  3570,  3584,  3600,
         3620,  3630,  3635,  3640,  3649,  3650,  3660,  3680,  3700,
         3720,  3745,  3750,  3760,  3780,  3792,  3800,  3816,  3840,
         3850,  3880,  3900,  3930,  3934,  3960,  3968,  3970,  3986,
         3990,  4000,  4032,  4040,  4046,  4050,  4075,  4079,  4080,
         4095,  4100,  4120,  4130,  4160,  4200,  4240,  4260,  4280,
         4300,  4320,  4340,  4350,  4352,  4360,  4370,  4400,  4410,
         4500,  4510,  4520,  4560,  4600,  4632,  4640,  4646,  4700,
         4750,  4770,  4775,  4785,  4800,  4815,  4820,  4840,  4880,
         4900,  4920,  4950,  4960,  4990,  4992,  4995,  5000,  5010,
         5020,  5040,  5076,  5136,  5150,  5170,  5200,  5300,  5320,
         5360,  5400,  5450,  5495,  5500,  5600,  5640,  5680,  5700,
         5720,  5750,  5800,  5828,  5830,  5850,  5880,  5885,  5900,
         5948,  5960,  5985,  6000,  6020,  6040,  6050,  6060,  6100,
         6210,  6240,  6254,  6300,  6321,  6325,  6350,  6360,  6400,
         6420,  6440,  6450,  6480,  6500,  6525,  6540,  6550,  6600,
         6615,  6650,  6660,  6670,  6710,  6720,  6750,  6800,  6825,
         6840,  6862,  6900,  6930,  7000,  7020,  7085,  7152,  7155,
         7160,  7200,  7231,  7260,  7320,  7350,  7410,  7420,  7424,
         7440,  7475,  7482,  7500,  7600,  7680,  7686,  7700,  7770,
         7800,  7950,  7980,  8000,  8050,  8080,  8100,  8150,  8250,
         8372,  8400,  8500,  8520,  8580,  8800,  8875,  8880,  8960,
         9000,  9166,  9500,  9620,  9667,  9800,  9860,  9960, 10240,
        10269, 10360, 10500, 10700, 11175, 11410, 11440, 11460, 12090,
        12900, 12944, 13200, 15600, 16200]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4])]

# Min-Max Scaling (Normalization)

In [38]:
from sklearn.preprocessing import MinMaxScaler

df=pd.read_excel("numpy_data.xlsx")
min_max=MinMaxScaler(feature_range=(-1,1))

# Select only numerical columns for scaling
numerical_cols = df.select_dtypes(include=['number']).columns
df_min_max=min_max.fit_transform(df[numerical_cols])

In [52]:
df # Print all data of xcel file

             Name  University  ATTENDANCE RESULT GRADE  TOTAL NUMBER
0         Bhupesh  IIT KANPUR          78   PASS    A+            90
1          Suresh     IIT BHU          69   PASS     B            80
2          Mukesh   IIT PATNA          79   FAIL     A            45
3          Denesh        IITM          94   PASS    B+            78
4          Nitesh         PSU          49   FAIL     C            34
5         Abhijay        PSIT          97   FAIL     D            42
6   Jatin(Gandhi)         LPU          80   PASS     E            67
7            Sami       AMITY          60   FAIL     G            35
8            Amit          DU          27   PASS     D            56
9         Abishek         KGI          45   PASS    A+            90
10         Ashish        MPGI          36   FAIL    B+            80
11       Satendra          JP          46   PASS     A            85
12        Nishant        SKIM          87   FAIL     F            23
13       Shailesh        SISE          89   FAIL     D            12
14          Naman        DISE          70   FAIL     E            23

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          15 non-null     object
 1   University    15 non-null     object
 2   ATTENDANCE    15 non-null     int64
 3   RESULT        15 non-null     object
 4   GRADE         15 non-null     object
 5   TOTAL NUMBER  15 non-null     int64
dtypes: int64(2), object(4)
memory usage: 852.0+ bytes

In [43]:
df.GRADE

0     A+
1      B
2      A
3     B+
4      C
5      D
6      E
7      G
8      D
9     A+
10    B+
11     A
12     F
13     D
14     E
Name: GRADE, dtype: object

In [44]:
df.describe()

       ATTENDANCE  TOTAL NUMBER
count   15.000000     15.000000
mean    67.066667     56.000000
std     22.069587     27.079249
min     27.000000     12.000000
25%     47.500000     34.500000
50%     70.000000     56.000000
75%     83.500000     80.000000
max     97.000000     90.000000

In [45]:
df.head()

      Name  University  ATTENDANCE RESULT GRADE  TOTAL NUMBER
0  Bhupesh  IIT KANPUR          78   PASS    A+            90
1   Suresh     IIT BHU          69   PASS     B            80
2   Mukesh   IIT PATNA          79   FAIL     A            45
3   Denesh        IITM          94   PASS    B+            78
4   Nitesh         PSU          49   FAIL     C            34

In [46]:
print(df)

             Name  University  ATTENDANCE RESULT GRADE  TOTAL NUMBER
0         Bhupesh  IIT KANPUR          78   PASS    A+            90
1          Suresh     IIT BHU          69   PASS     B            80
2          Mukesh   IIT PATNA          79   FAIL     A            45
3          Denesh        IITM          94   PASS    B+            78
4          Nitesh         PSU          49   FAIL     C            34
5         Abhijay        PSIT          97   FAIL     D            42
6   Jatin(Gandhi)         LPU          80   PASS     E            67
7            Sami       AMITY          60   FAIL     G            35
8            Amit          DU          27   PASS     D            56
9         Abishek         KGI          45   PASS    A+            90
10         Ashish        MPGI          36   FAIL    B+            80
11       Satendra          JP          46   PASS     A            85
12        Nishant        SKIM          87   FAIL     F            23
13       Shailesh        SISE          89   FAIL     D            12
14          Naman        DISE          70   FAIL     E            23

In [47]:
print(min_max)

MinMaxScaler(feature_range=(-1, 1))

In [48]:
print(numerical_cols)

Index(['ATTENDANCE', 'TOTAL NUMBER'], dtype='object')

In [49]:
print(df_min_max)

[[ 0.45714286  1.        ]
 [ 0.2         0.74358974]
 [ 0.48571429 -0.15384615]
 [ 0.91428571  0.69230769]
 [-0.37142857 -0.43589744]
 [ 1.         -0.23076923]
 [ 0.51428571  0.41025641]
 [-0.05714286 -0.41025641]
 [-1.          0.12820513]
 [-0.48571429  1.        ]
 [-0.74285714  0.74358974]
 [-0.45714286  0.87179487]
 [ 0.71428571 -0.71794872]
 [ 0.77142857 -1.        ]
 [ 0.22857143 -0.71794872]]

# Standerdization (Z-score Scaling)

In [58]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

df=pd.read_csv("Housing.csv")

std_scaler=StandardScaler()
df_std_scaler=std_scaler.fit_transform(std_scaler.fit_transform(df[["area","bedrooms","bathrooms"]]))

In [59]:
print(df)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]

In [60]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [61]:
print(df_std_scaler)

[[ 1.04672629  1.40341936  1.42181174]
 [ 1.75700953  1.40341936  5.40580863]
 [ 2.21823241  0.04727831  1.42181174]
 ...
 [-0.70592066 -1.30886273 -0.57018671]
 [-1.03338891  0.04727831 -0.57018671]
 [-0.5998394   0.04727831 -0.57018671]]

In [66]:
df.index

RangeIndex(start=0, stop=545, step=1)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [70]:
df.get

<bound method NDFrame.get of         price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]>

In [71]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [72]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [73]:
std_scaler.mean_

array([-1.56449777e-16, -1.82524739e-16, -2.60749628e-17])

In [79]:
df_std_scaler.mean

# Transformation pipeline

> Building a Numerical pipeline

In [93]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer # Corrected typo
from sklearn.preprocessing import StandardScaler
import pandas as pd

data=pd.read_csv("Housing.csv")

# The line data.fit_transform(data) is incorrect and not needed here.
# The pipeline will handle the fitting and transforming.

data_pipeline=Pipeline([
    ("impute",SimpleImputer(strategy="median")),
    ("standerdize",StandardScaler()),
])

# To use the pipeline, you would typically call fit_transform on your data,
# for example, data_processed = data_pipeline.fit_transform(data.select_dtypes(include=['number']))
# if you only want to process numerical columns.

In [94]:
print(data_pipeline)

Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                ('standerdize', StandardScaler())])

In [95]:
data_pipeline.fit_transform(data[['area','bedrooms','bathrooms']])

array([[ 1.04672629,  1.40341936,  1.42181174],
       [ 1.75700953,  1.40341936,  5.40580863],
       [ 2.21823241,  0.04727831,  1.42181174],
       ...,
       [-0.70592066, -1.30886273, -0.57018671],
       [-1.03338891,  0.04727831, -0.57018671],
       [-0.5998394 ,  0.04727831, -0.57018671]])

In [96]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [97]:
from sklearn.pipeline import make_pipeline

data_pipeline=make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

In [98]:
data_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

In [100]:
make_pipeline()

Pipeline(steps=[])

In [101]:
make_pipeline

# Using make_pipeline

In [119]:
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

data=pd.read_csv("Housing.csv")

# Re-initialize data_pipeline to ensure it's a Pipeline object
data_pipeline=make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

# The previous `data_pipeline` was defined to handle numerical columns.
# To avoid errors with categorical columns, we'll select only numerical ones for this pipeline.
# The column name '   guestroom   ' also had extra whitespace, which is corrected here.
# data_pipeline_transformed = data_pipeline.fit_transform(data[['area','bedrooms','bathrooms']])
# print(data_pipeline_transformed)

In [120]:
data_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

# Applying the pipeline

In [126]:
data_num_prepared=data_pipeline.fit_transform(data[['area']])
print(data_num_prepared[:20].round(10))

[[ 1.04672629]
 [ 1.75700953]
 [ 2.21823241]
 [ 1.08362412]
 [ 1.04672629]
 [ 1.08362412]
 [ 1.58174483]
 [ 5.09626319]
 [ 1.36035785]
 [ 0.27648408]
 [ 3.71259454]
 [ 0.3917898 ]
 [ 0.64546238]
 [-0.76126741]
 [ 1.22199098]
 [ 0.3917898 ]
 [ 0.66852353]
 [ 1.544847  ]
 [-0.25392224]
 [ 0.58550341]]

# Retrieving Feature Names

In [147]:
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

df=pd.read_csv('spotify_global_trends_2026.csv')

# Define a numerical pipeline
df_pipeline = make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

# Select the numerical columns from the spotify DataFrame for processing
# Based on common numerical columns in such datasets:
numerical_cols_spotify = ['streams', 'stream_change', '7day', 'days', 'viral_score']

# Apply the pipeline to transform the numerical data
data_transformed = df_pipeline.fit_transform(df[numerical_cols_spotify])

# Create a DataFrame from the transformed data with proper column names and index
df_streams_prepared=pd.DataFrame(
    data_transformed,
    columns=df_pipeline.get_feature_names_out(numerical_cols_spotify),
    index=df.index
)

In [149]:
df_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

In [148]:
df

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
174,Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
175,Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
176,Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
177,Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [150]:
data_transformed

array([[ 7.20491530e+00, -4.12746697e+00,  2.33578163e+00,
        -8.67561494e-01,  3.39146668e+00],
       [ 3.70612769e+00, -5.45796454e+00,  9.63581950e-01,
        -8.67561494e-01,  1.53905349e+00],
       [ 2.85709563e+00,  6.00704858e-01,  4.18705316e+00,
        -6.77575735e-01,  4.16108805e+00],
       [ 2.54689653e+00, -4.16254438e+00,  2.83040007e-01,
        -8.67561494e-01,  7.30205796e-01],
       [ 2.43557836e+00, -3.46593665e+00,  1.43239803e-01,
        -8.67561494e-01,  5.88235523e-01],
       [ 2.08439258e+00, -2.84850054e+00, -9.22017694e-02,
        -8.67561494e-01,  3.17915366e-01],
       [ 2.07579185e+00,  4.91209996e-02,  3.77774562e+00,
        -7.50647181e-01,  3.65857345e+00],
       [ 2.06028401e+00, -3.68266456e+00,  5.68175331e-03,
        -8.67561494e-01,  3.97854829e-01],
       [ 1.94681625e+00, -3.37961847e+00, -8.38622814e-02,
        -8.67561494e-01,  2.98878554e-01],
       [ 1.94157372e+00, -2.64802256e+00, -1.81364342e-01,
        -8.67561494e-01,  2.13670555e-01],
       [ 1.88093149e+00, -3.28872329e+00, -1.24787784e-01,
        -8.67561494e-01,  2.50967176e-01],
       [ 1.82884839e+00, -2.70914863e+00, -2.23198699e-01,
        -8.67561494e-01,  1.56040570e-01],
       [ 1.73245652e+00,  2.47433033e-01,  2.81509959e+00,
        -5.23313794e-01,  2.76169698e+00],
       [ 1.71196435e+00,  2.13571795e-01,  2.96546219e+00,
        -1.54708945e-01,  2.88764999e+00],
       [ 1.58176131e+00,  4.31182869e-01,  2.65912856e+00,
         3.69781655e-01,  2.59825051e+00],
       [ 1.50221302e+00, -3.02590970e-01,  3.34463298e+00,
        -8.33461486e-01,  3.17511781e+00],
       [ 1.48064724e+00, -2.50600517e+00, -4.03419197e-01,
        -8.67561494e-01, -6.60183995e-02],
       [ 1.44304152e+00,  4.07180286e-01,  2.59370904e+00,
        -5.85018570e-01,  2.51529330e+00],
       [ 1.41577645e+00, -2.33508051e+00, -4.54309346e-01,
        -8.67561494e-01, -1.22342402e-01],
       [ 1.39906236e+00,  9.92161845e-02,  2.34056473e+00,
        -6.93813834e-01,  2.28827608e+00],
       [ 1.31516387e+00, -3.27932419e+00, -3.75893064e-01,
        -8.67561494e-01, -7.38071455e-02],
       [ 1.31305901e+00, -2.24757412e+00, -5.11061817e-01,
        -8.67561494e-01, -1.90947731e-01],
       [ 1.27764291e+00,  1.43527518e-01,  2.36298263e+00,
        -5.94761430e-01,  2.28447968e+00],
       [ 1.16932664e+00,  1.87026289e-01,  2.31314362e+00,
        -2.71623258e-01,  2.22077736e+00],
       [ 9.82189595e-01,  3.03062972e-01,  1.77168246e+00,
        -1.54708945e-01,  1.71745013e+00],
       [ 9.79905799e-01,  3.33724577e-01,  1.63209266e+00,
         3.64910225e-01,  1.59645716e+00],
       [ 9.00681632e-01,  3.69385443e-01,  1.66865517e+00,
        -5.72028091e-01,  1.61292451e+00],
       [ 8.85211466e-01,  2.55609284e-01,  1.64837665e+00,
        -1.54708945e-01,  1.59246033e+00],
       [ 7.91161462e-01, -1.97241490e-01,  2.13699755e+00,
        -8.44828156e-01,  1.99652239e+00],
       [ 6.94370118e-01, -2.87158908e-02,  1.74597178e+00,
        -8.22094817e-01,  1.64035060e+00],
       [ 6.01812822e-01,  3.40851155e-01,  1.28345447e+00,
        -7.53894801e-01,  1.22324233e+00],
       [ 5.35988493e-01,  1.94054294e-01,  1.29406956e+00,
         6.21472191e-01,  1.21985575e+00],
       [ 4.69719176e-01,  1.72763807e-01,  1.19315462e+00,
         7.58720618e-02,  1.12006086e+00],
       [ 4.36361632e-01,  3.10370712e-01,  8.57553050e-01,
        -4.01528051e-01,  8.23854859e-01],
       [ 4.36207809e-01,  3.52645310e-01,  9.04672423e-01,
        -8.65089289e-02,  8.64520391e-01],
       [ 3.56550427e-01,  3.30177272e-01,  9.08758976e-01,
        -2.73247068e-01,  8.52857105e-01],
       [ 3.52802177e-01,  1.97276573e-01,  9.57944070e-01,
        -1.61204185e-01,  8.94621159e-01],
       [ 3.43644235e-01,  1.24216488e-01,  8.52675148e-01,
        -8.25342437e-01,  8.01958506e-01],
       [ 3.41948261e-01,  3.94516290e-01,  7.99925001e-01,
         2.23638763e-01,  7.56077126e-01],
       [ 2.39321859e-01, -6.77988467e-02,  1.17357975e+00,
        -7.05180504e-01,  1.05921240e+00],
       [ 2.15404003e-01,  3.96202691e-01,  6.28990108e-01,
         1.75813913e+00,  5.84313234e-01],
       [ 1.87549544e-01,  2.43322263e-01,  5.76544992e-01,
        -8.12351957e-01,  5.33706218e-01],
       [ 1.31091131e-01,  2.47506297e-01,  5.91457039e-01,
        -4.87589976e-01,  5.35817045e-01],
       [ 9.99985473e-02,  3.24801035e-01,  3.31849704e-01,
         1.86043915e+00,  3.05675801e-01],
       [ 9.44781971e-02,  4.82644759e-01,  1.95010384e-01,
         2.80472110e-01,  1.86441003e-01],
       [ 5.94293884e-02,  3.76068442e-01,  2.52960103e-01,
        -7.40904321e-01,  2.29804868e-01],
       [ 4.87630421e-02,  1.77940234e-01,  5.55817072e-01,
        -7.01932884e-01,  4.89334389e-01],
       [ 4.78510934e-02,  2.11864080e-01,  4.35025001e-01,
        -7.65261470e-01,  3.84837811e-01],
       [ 3.63630516e-02,  6.80617137e-02,  5.13348388e-01,
        -7.99361478e-01,  4.50291119e-01],
       [ 1.10215520e-02,  1.99799515e-01,  6.96846240e-01,
         7.26244420e-02,  6.03936653e-01],
       [-2.46069091e-03,  5.34758031e-01,  1.00697981e-01,
         4.16872142e-01,  8.64989747e-02],
       [-1.92838679e-02,  1.25200889e-01,  5.89982837e-01,
         2.57166789e+00,  5.05863565e-01],
       [-4.54745315e-02,  2.21247186e-01,  1.80422086e-01,
         2.59602504e+00,  1.47149260e-01],
       [-5.71061935e-02,  3.16159892e-01,  2.93688247e-02,
        -8.33461486e-01,  1.44729439e-02],
       [-6.41263147e-02,  2.40490280e-01,  3.00815363e-01,
         4.96438828e-01,  2.47570124e-01],
       [-7.91224551e-02,  2.69051209e-01,  2.86458958e-01,
        -5.94761430e-01,  2.32311007e-01],
       [-7.93571132e-02,  1.88981768e-01,  2.58945130e-01,
        -8.33461486e-01,  2.08503803e-01],
       [-1.10346102e-01,  4.50435288e-01,  3.26941864e-02,
        -7.31161462e-01,  7.19072449e-03],
       [-1.13696454e-01,  1.91997577e-01,  1.79958993e-01,
        -7.87994809e-01,  1.33737679e-01],
       [-1.42037496e-01,  1.72505385e-01,  4.48651109e-02,
         1.16544851e+00,  1.16578589e-02],
       [-1.46677290e-01,  2.49705546e-01,  1.58328283e-01,
        -6.46723347e-01,  1.08765942e-01],
       [-1.56043991e-01,  5.08626799e-01, -7.86968527e-02,
         7.59496033e-01, -9.77284077e-02],
       [-1.90991560e-01,  4.43115559e-01,  4.84638334e-03,
        -4.24261390e-01, -3.22412713e-02],
       [-2.07739395e-01,  2.29731145e-01,  7.29997475e-02,
         2.22904400e+00,  2.34254740e-02],
       [-2.09035115e-01,  1.21331223e-01,  1.74599107e-01,
         1.64284862e+00,  1.10925117e-01],
       [-2.10292380e-01,  2.55737162e-01,  1.94472593e-01,
         1.32782950e+00,  1.27849156e-01],
       [-2.24575129e-01,  5.97725015e-01, -1.58819578e-01,
         1.21338739e-01, -1.79997384e-01],
       [-2.45267417e-01,  1.84278227e-01, -1.40967572e-02,
        -2.61880399e-01, -5.89533699e-02],
       [-2.45333341e-01,  4.08096751e-01, -1.61227246e-01,
        -7.31161462e-01, -1.86035889e-01],
       [-2.60495076e-01,  2.03635879e-01,  1.74214744e-02,
         2.53107264e+00, -3.46367953e-02],
       [-2.78998530e-01,  4.01435065e-01, -1.83820711e-01,
         5.19172166e-01, -2.11969637e-01],
       [-2.79007163e-01,  3.54931143e-01, -1.55438756e-01,
         3.32836331e+00, -1.87459073e-01],
       [-2.85020374e-01,  9.34283371e-02,  2.52956290e-01,
         2.23638763e-01,  1.64106379e-01],
       [-3.02115880e-01,  3.66398940e-01, -1.63266796e-01,
         7.33515074e-01, -1.98627209e-01],
       [-3.28990897e-01,  3.96566347e-01, -1.79309713e-01,
        -1.77442284e-01, -2.17608489e-01],
       [-3.32538236e-01,  2.29355501e-01, -9.00289409e-02,
        -1.51461325e-01, -1.41177292e-01],
       [-3.35713576e-01,  3.47658037e-01, -1.70619959e-01,
         7.78981752e-01, -2.11385724e-01],
       [-3.38360738e-01,  4.59667870e-01, -3.21364202e-01,
         8.60172247e-01, -3.42081587e-01],
       [-3.49797767e-01,  2.13513184e-01, -1.80177319e-01,
         7.72486512e-01, -2.22326192e-01],
       [-3.52844398e-01,  1.79607987e-01,  5.20960872e-02,
         5.84124563e-01, -2.23032295e-02],
       [-3.52902474e-01,  2.21407035e-01, -2.95186446e-01,
         4.31486431e-01, -3.22246516e-01],
       [-3.52999790e-01,  1.49809564e-01,  1.30785685e-01,
        -7.76628139e-01,  4.56277785e-02],
       [-3.56000117e-01,  3.39561711e-01, -3.07178164e-01,
        -2.39147060e-01, -3.33194019e-01],
       [-3.59882570e-01,  4.48770199e-01, -2.84071346e-01,
        -7.49023371e-01, -3.13978187e-01],
       [-3.70670561e-01,  3.83422804e-01, -2.83840839e-01,
         2.82095920e-01, -3.15836649e-01],
       [-3.79167694e-01,  5.03892619e-01, -4.02613984e-01,
         1.28723425e+00, -4.20036255e-01],
       [-3.80311947e-01,  1.61824842e-01, -1.35241521e-01,
         1.40414857e+00, -1.89336994e-01],
       [-3.91831381e-01,  3.22295410e-01, -2.23856596e-01,
        -4.77847117e-01, -2.68066870e-01],
       [-3.92079381e-01,  2.93927631e-01, -2.72153286e-01,
        -4.26660614e-02, -3.09825835e-01],
       [-3.96855731e-01,  2.10923638e-01, -1.36522652e-01,
         1.62498671e+00, -1.93598764e-01],
       [-4.02309373e-01,  2.54603570e-01, -2.14576364e-01,
         7.22148405e-01, -2.62050369e-01],
       [-4.15436882e-01,  5.12657645e-01, -4.20479809e-01,
        -3.56061374e-01, -4.42383603e-01],
       [-4.15661337e-01,  4.82993761e-01, -4.15440726e-01,
        -7.76628139e-01, -4.38074384e-01],
       [-4.19890676e-01, -3.20021093e-02, -6.86410433e-02,
        -8.56194825e-01, -1.39365830e-01],
       [-4.25600165e-01,  3.90243007e-01, -4.24463415e-01,
        -2.81366118e-01, -4.47762455e-01],
       [-4.33539298e-01,  4.24570470e-01, -4.88248764e-01,
         7.58720618e-02, -5.04365167e-01],
       [-4.36100132e-01,  4.37334372e-01, -3.72224888e-01,
        -6.64585256e-01, -4.04649010e-01],
       [-4.37229473e-01,  4.28516064e-01, -4.23201867e-01,
        -6.72704305e-01, -4.48890914e-01],
       [-4.37728612e-01,  2.44551764e-01, -2.54421951e-01,
        -2.89485167e-01, -3.03218536e-01],
       [-4.39985724e-01,  3.07061848e-01, -3.77349935e-01,
         3.70021577e+00, -4.09816361e-01],
       [-4.45095619e-01,  2.93149702e-01, -2.98404527e-01,
        -2.80517723e-02, -3.42609369e-01],
       [-4.56116699e-01,  3.47772595e-01, -3.99955878e-01,
        -7.68509090e-01, -4.32416672e-01],
       [-4.58649279e-01,  5.54881624e-01, -3.59558634e-01,
         1.52593431e+00, -3.98010427e-01],
       [-4.59882215e-01,  4.32902573e-01, -5.36631937e-01,
        -8.48851190e-02, -5.51175778e-01],
       [-4.61867783e-01,  3.58290626e-01, -2.61421728e-01,
         4.17720537e-02, -3.13867870e-01],
       [-4.63226288e-01,  4.45160288e-01, -4.44466539e-01,
        -3.69051853e-01, -4.72214493e-01],
       [-4.68562993e-01,  3.75635519e-01, -3.94356473e-01,
         1.06639611e+00, -4.29954539e-01],
       [-4.80740882e-01,  8.75325919e-02,  5.29720125e-02,
        -8.44828156e-01, -4.59397949e-02],
       [-4.91725077e-01,  6.15398930e-01, -1.46272378e+00,
        -7.76628139e-01, -1.35707263e+00],
       [-5.02163043e-01,  1.95554206e-01, -3.75986479e-01,
         3.09700688e-01, -4.20497578e-01],
       [-5.06136534e-01,  3.77257981e-01, -4.69948789e-01,
         2.86557748e+00, -5.02406418e-01],
       [-5.12236858e-01,  3.69730449e-01, -4.68660552e-01,
        -7.31161462e-01, -5.02457310e-01],
       [-5.20136751e-01, -1.36574992e-01, -1.40549887e-02,
        -8.56194825e-01, -1.11341762e-01],
       [-5.25483658e-01,  2.25499156e-01, -3.39457068e-01,
         1.07289134e+00, -3.93396603e-01],
       [-5.29260162e-01,  5.57920100e-02,  3.63226731e-02,
        -8.44828156e-01, -6.95729176e-02],
       [-5.31598109e-01,  2.94742858e-01, -4.45139168e-01,
        -5.26561414e-01, -4.85835630e-01],
       [-5.32872640e-01,  3.19841735e-01, -5.05283899e-01,
         3.18059660e+00, -5.38022998e-01],
       [-5.40319698e-01,  3.58826118e-01, -4.14830836e-01,
        -6.75951925e-01, -4.61323121e-01],
       [-5.45497871e-01,  2.92732763e-01, -5.48476513e-01,
        -6.58090016e-01, -5.77734452e-01],
       [-5.46964680e-01,  1.87521819e-01, -3.87385987e-01,
        -3.17089936e-01, -4.38887610e-01],
       [-5.47906451e-01,  3.08591066e-01, -5.47365748e-01,
        -6.80823355e-01, -5.77234511e-01],
       [-5.50324450e-01,  2.35836025e-01, -3.62520385e-01,
         7.67204568e-03, -4.18053108e-01],
       [-5.51591132e-01,  3.55574533e-01, -6.20509841e-01,
        -5.93137620e-01, -6.41108516e-01],
       [-5.52376726e-01,  2.14544206e-01, -5.10062493e-01,
        -4.10422515e-02, -5.45869971e-01],
       [-5.52470904e-01,  3.45333573e-01, -5.61243115e-01,
        -8.36709106e-01, -5.90090320e-01],
       [-5.59740594e-01,  2.88535408e-01, -5.13045907e-01,
        -4.04775671e-01, -5.49851085e-01],
       [-5.60055303e-01,  6.51977616e-02, -3.60783266e-01,
        -6.40228107e-01, -4.18408754e-01],
       [-5.61918441e-01,  2.28570911e-01, -4.22726296e-01,
        -7.87994809e-01, -4.72261493e-01],
       [-5.69128486e-01,  2.36520710e-01, -3.33787124e-01,
         1.28398663e+00, -3.96823891e-01],
       [-5.69400815e-01,  3.43845650e-01, -5.99158859e-01,
        -1.56332755e-01, -6.26065391e-01],
       [-5.71914560e-01,  2.43988298e-01, -4.08441643e-01,
         4.42853101e-01, -4.61830995e-01],
       [-5.82787311e-01,  2.02041390e-01, -4.87273877e-01,
         2.72353061e-01, -5.31988535e-01],
       [-5.82816349e-01,  3.31101729e-01, -8.49902607e-01,
         3.51919746e-01, -8.45180099e-01],
       [-5.83543082e-01,  1.60498100e-01, -3.38727072e-01,
        -6.75951925e-01, -4.03839525e-01],
       [-5.84126981e-01,  1.93303006e-01, -3.49401783e-01,
        -6.15870959e-01, -4.13170154e-01],
       [-5.84882752e-01,  2.86366797e-01, -4.62763048e-01,
        -6.79199545e-01, -5.11219294e-01],
       [-5.86698017e-01,  4.00864939e-01, -1.07600398e+00,
         7.96843661e-01, -1.04119396e+00],
       [-5.89312217e-01,  2.90617435e-01, -4.00119313e-01,
        -6.53994001e-02, -4.57961544e-01],
       [-5.94477834e-01,  2.27858253e-01, -5.69621598e-01,
         1.78736770e+00, -6.05338211e-01],
       [-5.98428565e-01,  3.95511347e-01, -1.07836468e+00,
        -3.21961365e-01, -1.04547010e+00],
       [-6.02109321e-01,  3.10626470e-01, -6.11137579e-01,
         1.31081599e-01, -6.42649201e-01],
       [-6.02119524e-01,  2.41318828e-01, -5.15248892e-01,
        -2.29404201e-01, -5.59836427e-01],
       [-6.13948173e-01,  2.63769549e-01, -6.07681539e-01,
        -3.07347076e-01, -6.41922341e-01],
       [-6.17775689e-01,  3.23959166e-01, -5.57164187e-01,
         2.85343540e-01, -5.99022793e-01],
       [-6.25029684e-01,  3.60006333e-01, -1.28797616e+00,
        -5.40327308e-02, -1.23157555e+00],
       [-6.25547658e-01,  3.88685816e-01, -6.46949994e-01,
        -4.09647100e-01, -6.78049041e-01],
       [-6.26819049e-01,  3.50668517e-01, -5.68859193e-01,
         3.84395944e-01, -6.10848036e-01],
       [-6.27349581e-01,  1.08847056e-01, -1.91011132e-01,
        -8.44828156e-01, -2.84618947e-01],
       [-6.28500111e-01,  2.15528607e-01, -7.86309982e-01,
         4.65586439e-01, -7.98971064e-01],
       [-6.30172540e-01,  3.69960897e-01, -1.49145270e+00,
        -7.68509090e-01, -1.40828990e+00],
       [-6.33220741e-01,  2.76857144e-01, -6.27290549e-01,
         5.64638844e-01, -6.62533517e-01],
       [-6.35239271e-01,  4.16197073e-01, -1.09041047e+00,
         1.35953028e-01, -1.06289423e+00],
       [-6.36573447e-01,  2.45612092e-01, -6.34189977e-01,
         1.09562468e+00, -6.69131686e-01],
       [-6.37031776e-01,  3.35440284e-01, -5.98081024e-01,
        -4.61609017e-01, -6.38033432e-01],
       [-6.37355902e-01,  3.53262058e-01, -1.28514700e+00,
         2.85096319e+00, -1.23148304e+00],
       [-6.38615521e-01,  3.33888421e-01, -1.30037829e+00,
        -8.48075775e-01, -1.24487786e+00],
       [-6.41660582e-01,  2.09851321e-01, -5.78420540e-01,
        -8.38332916e-01, -6.21936390e-01],
       [-6.41891316e-01,  2.76268369e-01, -6.42085610e-01,
        -2.39147060e-01, -6.76965038e-01],
       [-6.47330831e-01,  3.74559206e-01, -1.71806743e+00,
         7.75734132e-01, -1.60727930e+00],
       [-6.51077512e-01,  3.83410816e-01, -1.11524575e+00,
        -7.84747189e-01, -1.08736407e+00],
       [-6.53646193e-01,  2.43153090e-01, -5.70077932e-01,
        -8.65089289e-02, -6.17017214e-01],
       [-6.54682927e-01,  3.25781439e-01, -6.38843092e-01,
        -7.40904321e-01, -6.76604302e-01],
       [-6.56112850e-01,  2.45413614e-01, -8.81875613e-01,
        -8.22094817e-01, -8.86773216e-01],
       [-6.58318165e-01,  2.91240844e-01, -5.48915169e-01,
        -1.33599416e-01, -5.99630954e-01],
       [-6.60496796e-01,  3.36112980e-01, -1.71888027e+00,
        -7.10051933e-01, -1.61049240e+00],
       [-6.65800539e-01,  2.58411960e-01, -5.90222654e-01,
        -4.32380439e-01, -6.36733436e-01],
       [-6.68813422e-01,  3.09755296e-01, -6.86331968e-01,
        -4.74599497e-01, -7.20313335e-01],
       [-6.69821118e-01,  3.12284898e-01, -1.30834914e+00,
         4.13624522e-01, -1.25771361e+00],
       [-6.71909496e-01,  3.46685625e-01, -1.32650284e+00,
        -8.62690065e-01, -1.27379045e+00],
       [-6.79376174e-01,  2.63472497e-01, -6.03820120e-01,
         4.11428730e+00, -6.51066166e-01],
       [-6.79648503e-01,  2.23145387e-01, -8.54911534e-01,
         9.04015114e-01, -8.67974399e-01],
       [-6.81698425e-01,  2.43149094e-01, -1.05171621e+00,
        -6.22366198e-01, -1.03833666e+00],
       [-6.81757286e-01,  3.30010763e-01, -6.59011038e-01,
        -3.08970886e-01, -6.99186202e-01],
       [-6.92805050e-01,  2.56357907e-01, -6.28027131e-01,
        -5.37928083e-01, -6.74533889e-01],
       [-6.98642463e-01,  2.69301639e-01, -8.66859231e-01,
        -2.99228027e-01, -8.81915709e-01],
       [-7.01962992e-01,  2.00372306e-01, -1.49469089e+00,
        -3.33328035e-01, -1.42477881e+00],
       [-7.07286355e-01,  2.46736360e-01, -8.82884643e-01,
         3.74653085e-01, -8.97404738e-01],
       [-7.07575950e-01,  2.60900269e-01, -5.99996829e-01,
        -5.34680463e-01, -6.53142566e-01]])

In [151]:
df_streams_prepared

      streams  stream_change      7day      days  viral_score
0    7.204915      -4.127467  2.335782 -0.867561     3.391467
1    3.706128      -5.457965  0.963582 -0.867561     1.539053
2    2.857096       0.600705  4.187053 -0.677576     4.161088
3    2.546897      -4.162544  0.283040 -0.867561     0.730206
4    2.435578      -3.465937  0.143240 -0.867561     0.588236
..        ...            ...       ...       ...          ...
173 -0.692805       0.256358 -0.628027 -0.537928    -0.674534
174 -0.698642       0.269302 -0.866859 -0.299228    -0.881916
175 -0.701963       0.200372 -1.494691 -0.333328    -1.424779
176 -0.707286       0.246736 -0.882885  0.374653    -0.897405
177 -0.707576       0.260900 -0.599997 -0.534680    -0.653143

[178 rows x 5 columns]

In [152]:
numerical_cols_spotify

['streams', 'stream_change', '7day', 'days', 'viral_score']

In [157]:
print(numerical_cols_spotify[:1])

['streams']

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_name           178 non-null    object
 1   artist_name          178 non-null    object
 2   streams              178 non-null    int64
 3   stream_change        178 non-null    int64
 4   7day                 178 non-null    int64
 5   genre                178 non-null    object
 6   country              178 non-null    object
 7   pos                  178 non-null    int64
 8   days                 178 non-null    int64
 9   viral_score          178 non-null    int64
 10  trend                178 non-null    object
 11  popularity_category  178 non-null    object
 12  longevity            178 non-null    object
dtypes: int64(6), object(7)
memory usage: 18.2+ KB

In [169]:
df.head()

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New

In [170]:
df.describe()

,streams,stream_change,7day,pos,days,viral_score
count,1.780000e+02,1.780000e+02,1.780000e+02,178.000000,178.000000,1.780000e+02
mean,2.093366e+06,-2.719877e+05,1.244096e+07,96.123596,536.275281,1.453433e+07
std,1.277789e+06,7.528285e+05,5.786175e+06,56.151997,617.572830,6.699639e+06
min,1.191777e+06,-4.369341e+06,2.523194e+06,1.000000,2.000000,3.774959e+06
25%,1.350050e+06,-1.267320e+05,9.277907e+06,48.250000,80.000000,1.067544e+07
50%,1.590738e+06,-7.408450e+04,1.080256e+07,96.500000,346.500000,1.257072e+07
75%,2.202585e+06,-5.174750e+03,1.354278e+07,141.750000,766.250000,1.608216e+07
max,1.127383e+07,1.899990e+05,3.659983e+07,200.000000,3070.000000,4.233369e+07